version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "online-resume-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-tprtnk5iw2ya"
s3_prefix = "online-resume-app"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
